### ISSUE TITLE
README updates, English translation, differences with Ponto/Jockey

### ISSUE THREAD

**Issue by dvoiss** [pengwei1024/JsBridge#1]
Hi Pengwei,

Is there a possibility of an English translation of the `README` and maybe the linked blogpost? Google translate doesn't do a very good job.

Also is `JsBridge` better or does it have different benefits than other projects that use the `WebView` `javascript:` method of bridging? Two projects I'm familiar with that do the same are: [Ponto](https://github.com/Wikia/ponto) and [JockeyJS](https://github.com/tcoulter/jockeyjs). Neither has been updated in a while though.

One of the things I like about Jockey is it's [service](https://github.com/tcoulter/jockeyjs/blob/master/JockeyJS.Android/src/main/java/com/jockeyjs/JockeyService.java) component. But I've also noticed that sending two payloads from the `WebView` back to the java receiver in quick succession results in the first payload being lost.

Thanks!

**Comment by pengwei1024** [comment]
I have a rough understanding of `Ponto` and `JockeyJS`, They all need to import an external js file, They need to determine equipment，android or ios or others，But JsBridge not need to do，In order to be compatible IOS UiWebView， We had to use a custom protocol， such as jockey://type/id，client to intercept this request and perform operations，This is not a good way to android。
So my solution is injected through js，this benefit is not to consider the issue Platform，android platform can use the  the best way to achieve， such as android platform reimplement prompt(JSBridge using this method)，each platform own injection js objects，It does not depend on js file，also does not exist Incompatibility，For more details, you can read the code。The English version of README available later，thanks。
